baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Commands cheat sheet'

theme = ["github.com/dzello/reveal-hugo"]
# theme = "reveal-hugo"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
